#!/bin/sh
while getopts a:o:i:*s option
do
    case "${option}"
    in
    a) APIKEY="${OPTARG}";;
    i) ALBUMDIR=$(realpath "${OPTARG}"); SPECTROGRAMSDIR="$ALBUMDIR/Spectrograms";;
    o) SPECTROGRAMSDIR=$(realpath "${OPTARG}/${ALBUMDIR##*/}"); BASESPECTROGRAMSDIR=${OPTARG};;
    s) SMALL="true";;
    *) 	    
    echo "Usage: "
    echo "csfru [options] -i ALBUMDIR"
    echo " "
    echo "Options: "
    echo "-a PTPIMGAPIKEY"
    echo "-o SPECTROGRAMSDIR (if not specified will output in ALBUMDIR)"
    echo "-u (whether to upload or not)"
    echo "-s (for small sized spectrograms)"
    exit
    ;;
    esac
done

if [ -z "$ALBUMDIR" ]
then
    echo "${0##*/}: has exited because an input directory was not specified"
    exit

elif [ ! -d "$ALBUMDIR" ]
then
    echo "-i error"
    echo "Please specify a directory that exists!"
    echo "Specified directory: "
    echo "$ALBUMDIR"
    exit
fi

if [ ! -d "$BASESPECTROGRAMSDIR" ]
then
    echo "-o error"
    echo "Please specify a directory that exists!"
    echo "Specified directory: "
    echo "$SPECTROGRAMSDIR"
    exit
fi

mkdir -p "$SPECTROGRAMSDIR"
for SONG in "$ALBUMDIR"/*.flac;
do
    SPECTROGRAMSONG="${SONG##*/}"
    SPECTROGRAM="${SPECTROGRAMSONG%.*}.png"
    if [ "$SMALL" ]
    then
        sox "$SONG" -n spectrogram -o "$SPECTROGRAMSDIR/$SPECTROGRAM"
    else
        sox "$SONG" -n remix 1 spectrogram -x 3000 -y 513 -z 120 -w Kaiser -o "$SPECTROGRAMSDIR/$SPECTROGRAM"
    fi
    echo "$SPECTROGRAMSONG Done!"
done

if [ "$APIKEY" ]
then
    echo "Creating albumdescription.txt"
    echo "Tracklist: " > "$SPECTROGRAMSDIR/albumdescription.txt"
    echo " " >> "$SPECTROGRAMSDIR/albumdescription.txt"
    for SPECTROGRAM in "$SPECTROGRAMSDIR"/*.png;
    do
        echo "${SPECTROGRAM%.*}" >> "$SPECTROGRAMSDIR/albumdescription.txt"
    done
    xclip -sel c < "$SPECTROGRAMSDIR/albumdescription.txt"
    echo "Copied albumdescription.txt to clipboard"
    read -p "Press enter when done pasting." input
    printf "[spoiler=Spectrograms]" > "$SPECTROGRAMSDIR/releasedescription.txt"
    for SPECTROGRAM in "$SPECTROGRAMSDIR"/*.png;
    do
	SONGNAME="${SPECTROGRAM##*/}"
        echo "Uploading ${SONGNAME%.*}"
        if [[ "$SPECTROGRAM" == *","* ]]
        then
            SPECTROGRAMLINK=$(curl -F "file-upload[0]=@\"$SPECTROGRAM\"" -F api_key="$APIKEY" "https://ptpimg.me/upload.php" | awk -F ":|," '!(NR%4){print p$2}{p=$2}'| sed 's/^.*"\(.*\)" "\(.*\)".*$/https:\/\/ptpimg.me\/\1.\2/')
        else
            SPECTROGRAMLINK=$(curl -F "file-upload[0]=@$(realpath "$SPECTROGRAM")" -F api_key="$APIKEY" "https://ptpimg.me/upload.php" | awk -F ":|," '!(NR%4){print p$2}{p=$2}'| sed 's/^.*"\(.*\)" "\(.*\)".*$/https:\/\/ptpimg.me\/\1.\2/')
        fi
        echo "${SONGNAME%.*} Done!"
        echo "${SONGNAME%.*}" >> "$SPECTROGRAMSDIR/releasedescription.txt"
        echo "[img]$SPECTROGRAMLINK[/img]" >> "$SPECTROGRAMSDIR/releasedescription.txt"
        echo " " >> "$SPECTROGRAMSDIR/releasedescription.txt"
    done
    echo "[/spoiler]" >> "$SPECTROGRAMSDIR/releasedescription.txt"
    xclip -sel c < "$SPECTROGRAMSDIR/releasedescription.txt"
    echo "Copied releasedescription.txt to clipboard!"
fi
