#!/bin/sh
while getopts a:o:i:*s option
do
    case "${option}"
    in
    a) APIKEY="${OPTARG}";;
    i) ALBUMFOLDER=$(realpath "${OPTARG}"); SPECTROGRAMSFOLDER="$ALBUMFOLDER/Spectrograms";;
    o) SPECTROGRAMSFOLDER=$(realpath "${OPTARG}/${ALBUMFOLDER##*/}");;
    s) SMALL="true";;
    *) 	    
    echo "Usage: "
    echo "csfru [options] -i ALBUMFOLDER"
    echo " "
    echo "Options: "
    echo "-a PTPIMGAPIKEY"
    echo "-o SPECTROGRAMSFOLDER (if not specified will output in ALBUMFOLDER)"
    echo "-u (whether to upload or not)"
    echo "-s (for small sized spectrograms)"
    exit
    ;;
    esac
done

if [ -z "$ALBUMFOLDER" ]
then
    echo "${0##*/}: has exited because an input directory was not specified"
    exit

elif [ ! -d "$ALBUMFOLDER" ]
then
    echo "-i error"
    echo "Please specify a directory that exists!"
    echo "Specified directory: "
    echo "$ALBUMFOLDER"
    exit
fi

curl_check() {
    if [[ "$SONG" == *","* ]]
    then
        SONGLINK=$(curl -F "file-upload[0]=@\"$SONG\"" -F api_key="$APIKEY" "https://ptpimg.me/upload.php" | awk -F ":|," '!(NR%4){print p$2}{p=$2}'| sed 's/^.*"\(.*\)" "\(.*\)".*$/https:\/\/ptpimg.me\/\1.\2/')
    else
	SONGLINK=$(curl -F "file-upload[0]=@$(realpath "$SONG")" -F api_key="$APIKEY" "https://ptpimg.me/upload.php" | awk -F ":|," '!(NR%4){print p$2}{p=$2}'| sed 's/^.*"\(.*\)" "\(.*\)".*$/https:\/\/ptpimg.me\/\1.\2/')
    fi
}


chosensox() {
    if [ "$SMALL" ]
    then
	sox "$SONG" -n spectrogram -o "$SPECTROGRAMSFOLDER/$SPECTROGRAM"
    else
        sox "$SONG" -n remix 1 spectrogram -x 3000 -y 513 -z 120 -w Kaiser -o "$SPECTROGRAMSFOLDER/$SPECTROGRAM"
    fi
}

make_spectrograms()
{
    SPECTROGRAMSFOLDER=$1
    mkdir -p "$SPECTROGRAMSFOLDER"
    echo "Tracklist: " > "$SPECTROGRAMSFOLDER/albumdescription.txt"
    echo " " >> "$SPECTROGRAMSFOLDER/albumdescription.txt"
    for SONG in "$ALBUMFOLDER"/*.flac;
    do
	SPECTROGRAMSONG="${SONG##*/}"
	SPECTROGRAM="${SPECTROGRAMSONG%.*}.png"
	chosensox
	echo "$SPECTROGRAMSONG Done!"
	echo "${SPECTROGRAMSONG%.*}" >> "$SPECTROGRAMSFOLDER/albumdescription.txt"
    done
}

if [ -z "$SPECTROGRAMSFOLDER" ] 
then
    make_spectrograms "$SPECTROGRAMSFOLDER"

elif [ -d "$SPECTROGRAMSFOLDER" ]
then
    make_spectrograms "$SPECTROGRAMSFOLDER"

else
    echo "-o error"
    echo "Please specify a directory that exists!"
    echo "Specified directory: "
    echo "$SPECTROGRAMSFOLDER"
    exit
fi

if [ "$APIKEY" ]
then
    xclip -sel c < "$SPECTROGRAMSFOLDER/albumdescription.txt"
    echo "Copied albumdescription.txt to clipboard"
    read -p "Press enter when done pasting." input
    printf "[spoiler=Spectrograms]" > "$SPECTROGRAMSFOLDER/releasedescription.txt"
    for SONG in "$SPECTROGRAMSFOLDER"/*.png;
    do
	SONGNAME="${SONG##*/}"
        echo "Uploading ${SONGNAME%.*}"
        curl_check
	echo "${SONGNAME%.*} Done!"
        echo "${SONGNAME%.*}" >> "$SPECTROGRAMSFOLDER/releasedescription.txt"
        echo "[img]$SONGLINK[/img]" >> "$SPECTROGRAMSFOLDER/releasedescription.txt"
        echo " " >> "$SPECTROGRAMSFOLDER/releasedescription.txt"
    done
    echo "[/spoiler]" >> "$SPECTROGRAMSFOLDER/releasedescription.txt"
    xclip -sel c < "$SPECTROGRAMSFOLDER/releasedescription.txt"
    echo "Copied releasedescription.txt to clipboard!"
fi
